# Pratham Sharma's Kitty Configuration
# Author: Pratham Sharma

enable_audio_bell no
window_alert_on_bell no

#Fonts
font_family FiraCode Nerd Font
# font_family JetBrains Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13

# url
detect_urls yes
# url_color #ffff00
url_style straight
open_url_with default

# Theme
# background #1b1b27
# selection_background #ffffff
background_opacity 0.8
background_blur 1
confirm_os_window_close 0

# window padding
window_margin_width 8

# tabs
tab_bar_edge top
tab_bar_margin_width 1.0
tab_bar_margin_height 1.0 0.5
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}"

# styling tabs
active_tab_foreground #0da38a 
active_tab_background #1d202f
active_tab_font_style bold-italic
inactive_tab_foreground #ffffff
inactive_tab_background #292945
inactive_tab_font_style normal

# clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# keymaps
map ctrl+shift+i next_layout
map ctrl+enter new_window
map ctrl+shift+l next_window
map ctrl+shift+h previous_window

map ctrl+t new_tab
map ctrl+shift+w close_tab

map ctrl+shift+r load_config_file

# Advanced Layouts
enabled_layouts splits,stack,tall,fat,grid
# Zoom window (toggle between current layout and full screen)
map ctrl+shift+z toggle_layout stack

# Keyboard Hints (Mouse-free superpower)
# Open URLs
map ctrl+shift+e kitten hints
# Select a path and insert it into the terminal
map ctrl+shift+p>f kitten hints --type path --program -
# Select a line and insert it into the terminal
map ctrl+shift+p>l kitten hints --type line --program -

# BEGIN_KITTY_THEME
# Copland OS
include current-theme.conf
# END_KITTY_THEME

# Cursor
shell_integration no-cursor
cursor_shape beam
cursor_beam_thickness 4.5
cursor_blink_interval 0.5
cursor_stop_blinking_after 0
cursor_trail 1
cursor_trail_decay 0.08 0.25
cursor_trail_start_threshold 1
cursor_trail_color none

# Decay
# include decay.conf

# include oxocarbon.conf
# include eldritch.conf
# theme is already included in the BEGIN_KITTY_THEME block above
