add_newline = false
scan_timeout = 100
command_timeout = 800

format = "$directory$git_branch$git_status$cmd_duration\n$character"

[directory]
style = "bold #cdd6f4"
truncation_length = 3
truncate_to_repo = false
home_symbol = "~"
read_only = " 󰌾"
read_only_style = "bold #f38ba8"
format = "[$path]($style)[$read_only]($read_only_style) "

[directory.substitutions]
Documents = "󰈙 "
Downloads = "󰇚 "
Music = "󰝚 "
Pictures = "󰉏 "
Videos = "󰕧 "

[git_branch]
symbol = " "
style = "bold #89b4fa"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold #f5c2e7"
format = "([$all_status$ahead_behind]($style)) "

[cmd_duration]
min_time = 500
style = "bold #f9e2af"
format = "[$duration]($style) "

[character]
success_symbol = "[❯](bold #a6e3a1)"
error_symbol = "[❯](bold #f38ba8)"
vicmd_symbol = "[❮](bold #89b4fa)"
